version: '3'
services:
  nginx:
    image: nginx:latest
    container_name: webserver
    restart: unless-stopped
    ports:
      - 80:80
      - 443:443
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
      - ./ssl:/ssl/
  node:
    restart: always
    build: .
    ports:
      - 51005:51005
    depends_on: 
      - mongo
      - mysql
      - nginx
  mongo:
    image: mongo
    ports:
      - 27017:27017
    volumes:
      - mongodb:/data/db
  mysql:
    image: mysql
    restart: always
    env_file: ./.env
    environment:
       - MYSQL_ROOT_PASSWORD=$$(MYSQL_ROOT_PASSWORD)
       - MYSQL_DATABASE=$$(MYSQL_DATABASE)
    ports:
      - 3606:3606
    volumes: 
      - db-config:/etc/mysql
      - db-data:/var/lib/mysql
      - ./db/backup/files/:/data_backup/data
volumes:
 mongodb:
 db-config:
 db-data:
